//! CSS generator for math formulas

use crate::core::Result;
use serde::{Deserialize, Serialize};

/// CSS generator for math formulas
pub struct MathCssGenerator {
    config: MathCssConfig,
}

/// Configuration for math CSS generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MathCssConfig {
    /// Theme name
    pub theme: String,
    /// Font scaling factor
    pub font_scale: f32,
    /// Line height
    pub line_height: f32,
    /// Display math margin
    pub display_margin: String,
    /// Inline math padding
    pub inline_padding: String,
    /// Color scheme
    pub color_scheme: String,
}

impl Default for MathCssConfig {
    fn default() -> Self {
        Self {
            theme: "default".to_string(),
            font_scale: 1.0,
            line_height: 1.5,
            display_margin: "1.5em 0".to_string(),
            inline_padding: "0.2em 0.3em".to_string(),
            color_scheme: "auto".to_string(),
        }
    }
}

impl MathCssGenerator {
    /// Create a new CSS generator with default configuration
    pub fn new() -> Result<Self> {
        Self::with_config(MathCssConfig::default())
    }

    /// Create a CSS generator with custom configuration
    pub fn with_config(config: MathCssConfig) -> Result<Self> {
        Ok(Self { config })
    }

    /// Generate complete CSS for math formulas
    pub fn generate(&self) -> Result<String> {
        let mut css = String::new();

        // Header
        css.push_str("/*\n");
        css.push_str(" * Math Formula Styles\n");
        css.push_str(" * Generated by Peta Static Site Generator\n");
        css.push_str(" */\n\n");

        // Display styles
        css.push_str(&self.generate_display_styles());
        css.push('\n');

        // Inline styles
        css.push_str(&self.generate_inline_styles());
        css.push('\n');

        // KaTeX base styles
        css.push_str(&self.generate_katex_base_styles());
        css.push('\n');

        // Theme styles
        css.push_str(&self.generate_theme_styles());
        css.push('\n');

        // Responsive styles
        css.push_str(&self.generate_responsive_styles());
        css.push('\n');

        // Print styles
        css.push_str(&self.generate_print_styles());

        Ok(css)
    }

    /// Generate display math styles
    fn generate_display_styles(&self) -> String {
        format!(
            r#"/* Display Math Styles */
.math-display {{
    display: block;
    text-align: center;
    margin: {};
    padding: 0.5em 0;
    overflow-x: auto;
    overflow-y: hidden;
    line-height: {};
}}

.math-display .katex {{
    font-size: calc(1.1em * {});
    display: inline-block;
    max-width: 100%;
}}
"#,
            self.config.display_margin,
            self.config.line_height,
            self.config.font_scale
        )
    }

    /// Generate inline math styles
    fn generate_inline_styles(&self) -> String {
        format!(
            r#"/* Inline Math Styles */
.math-inline {{
    display: inline;
    white-space: nowrap;
    padding: {};
    line-height: {};
}}

.math-inline .katex {{
    font-size: calc(1em * {});
    vertical-align: middle;
}}
"#,
            self.config.inline_padding,
            self.config.line_height,
            self.config.font_scale
        )
    }

    /// Generate KaTeX base styles
    fn generate_katex_base_styles(&self) -> String {
        r#"/* KaTeX Base Styles */
.katex {
    font-family: 'KaTeX_Main', 'Times New Roman', serif;
    line-height: 1.1;
    text-indent: 0;
}

.katex-display {
    margin: 1em 0;
    text-align: center;
}

.katex-display > .katex {
    text-align: center;
}
"#.to_string()
    }

    /// Generate theme styles
    fn generate_theme_styles(&self) -> String {
        match self.config.theme.as_str() {
            "dark" => self.generate_dark_theme(),
            _ => self.generate_light_theme(),
        }
    }

    /// Generate light theme styles
    fn generate_light_theme(&self) -> String {
        r#"/* Light Theme */
@media (prefers-color-scheme: light) {
    .math-display {
        background: #f8fafc;
        border-radius: 4px;
    }

    .math-inline {
        color: #0f172a;
    }
}
"#.to_string()
    }

    /// Generate dark theme styles
    fn generate_dark_theme(&self) -> String {
        r#"/* Dark Theme */
@media (prefers-color-scheme: dark) {
    .math-display {
        background: #1e293b;
        border-radius: 4px;
    }

    .math-inline {
        color: #e2e8f0;
    }

    .katex {
        color: #e2e8f0;
    }
}
"#.to_string()
    }

    /// Generate responsive styles
    fn generate_responsive_styles(&self) -> String {
        r#"/* Responsive Styles */
@media (max-width: 768px) {
    .math-display {
        font-size: 0.9em;
        padding: 0.3em 0;
    }

    .math-inline {
        font-size: 0.95em;
    }
}

@media (max-width: 480px) {
    .math-display {
        font-size: 0.85em;
        overflow-x: scroll;
    }
}
"#.to_string()
    }

    /// Generate print styles
    fn generate_print_styles(&self) -> String {
        r#"/* Print Styles */
@media print {
    .math-display {
        page-break-inside: avoid;
        margin: 1em 0;
    }

    .math-inline {
        white-space: normal;
    }
}
"#.to_string()
    }

    /// Set theme
    pub fn set_theme(&mut self, theme: &str) {
        self.config.theme = theme.to_string();
    }

    /// Set font scale
    pub fn set_font_scale(&mut self, scale: f32) {
        self.config.font_scale = scale;
    }

    /// Get configuration
    pub fn config(&self) -> &MathCssConfig {
        &self.config
    }
}

impl Default for MathCssGenerator {
    fn default() -> Self {
        Self::new().expect("Failed to create MathCssGenerator")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_css_generator() {
        let generator = MathCssGenerator::new().unwrap();
        let css = generator.generate().unwrap();

        assert!(css.contains(".math-display"));
        assert!(css.contains(".math-inline"));
        assert!(css.contains("@media print"));
        assert!(css.contains("@media (max-width: 768px)"));
    }

    #[test]
    fn test_dark_theme() {
        let mut config = MathCssConfig::default();
        config.theme = "dark".to_string();
        let generator = MathCssGenerator::with_config(config).unwrap();
        let css = generator.generate().unwrap();

        assert!(css.contains("background: #1e293b"));
        assert!(css.contains("color: #e2e8f0"));
    }

    #[test]
    fn test_font_scale() {
        let mut config = MathCssConfig::default();
        config.font_scale = 1.2;
        let generator = MathCssGenerator::with_config(config).unwrap();
        let css = generator.generate().unwrap();

        assert!(css.contains("calc(1.1em * 1.2)"));
        assert!(css.contains("calc(1em * 1.2)"));
    }
}
