//! JavaScript generator for code block interactions

use crate::core::Result;
use serde::{Deserialize, Serialize};

/// JavaScript generator for code block functionality
pub struct JsGenerator {
    /// Configuration
    config: JsConfig,
}

/// Configuration for JavaScript generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsConfig {
    /// Enable copy functionality
    pub enable_copy: bool,
    /// Enable keyboard shortcuts
    pub enable_keyboard_shortcuts: bool,
    /// Enable line hover effects
    pub enable_line_hover: bool,
    /// Copy success duration in milliseconds
    pub copy_success_duration: u64,
}

impl Default for JsConfig {
    fn default() -> Self {
        Self {
            enable_copy: true,
            enable_keyboard_shortcuts: true,
            enable_line_hover: true,
            copy_success_duration: 2000,
        }
    }
}

impl JsGenerator {
    /// Create a new JavaScript generator with default configuration
    pub fn new() -> Self {
        Self::with_config(JsConfig::default())
    }

    /// Create a JavaScript generator with custom configuration
    pub fn with_config(config: JsConfig) -> Self {
        Self { config }
    }

    /// Generate complete JavaScript for code blocks
    pub fn generate(&self) -> Result<String> {
        let mut js = String::new();

        js.push_str("/**\n");
        js.push_str(" * Code Block Component JavaScript\n");
        js.push_str(" * Generated by Peta Static Site Generator\n");
        js.push_str(" */\n\n");

        // Copy functionality
        if self.config.enable_copy {
            js.push_str(&self.generate_copy_function());
        }

        // Line hover effects
        if self.config.enable_line_hover {
            js.push_str(&self.generate_line_hover_function());
        }

        // Keyboard shortcuts
        if self.config.enable_keyboard_shortcuts {
            js.push_str(&self.generate_keyboard_shortcuts_function());
        }

        // Initialization
        js.push_str(&self.generate_initialization());

        Ok(js)
    }

    /// Generate copy to clipboard function
    fn generate_copy_function(&self) -> String {
        let duration = self.config.copy_success_duration;

        format!(
            r#"
/**
 * Copy code to clipboard with enhanced feedback
 * @param button - The copy button element
 */
function copyCode(button) {{
    const codeBlock = button.closest('.code-block');
    const codeElement = codeBlock.querySelector('code');
    const text = codeElement.textContent;

    navigator.clipboard.writeText(text).then(() => {{
        const originalText = button.innerHTML;
        button.classList.add('copied');
        button.innerHTML = `
            <svg class="code-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="20 6 9 17 4 12"></polyline>
            </svg>
            <span class="copy-text">Copied!</span>
        `;

        // Visual feedback
        button.style.background = 'rgba(16, 185, 129, 0.2)';
        button.style.borderColor = 'rgba(16, 185, 129, 0.5)';

        setTimeout(() => {{
            button.innerHTML = originalText;
            button.classList.remove('copied');
            button.style.background = '';
            button.style.borderColor = '';
        }}, {});
    }}).catch(err => {{
        console.error('Failed to copy code:', err);
        // Show error feedback
        button.style.background = 'rgba(239, 68, 68, 0.2)';
        button.style.borderColor = 'rgba(239, 68, 68, 0.5)';
        button.innerHTML = `
            <svg class="code-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="15" y1="9" x2="9" y2="15"></line>
                <line x1="9" y1="9" x2="15" y2="15"></line>
            </svg>
            <span class="copy-text">Error</span>
        `;

        setTimeout(() => {{
            button.innerHTML = `
                <svg class="code-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                </svg>
                <span class="copy-text">Copy</span>
            `;
            button.style.background = '';
            button.style.borderColor = '';
        }}, {});
    }});
}}

"#,
            duration, duration
        )
    }

    /// Generate line hover effects function
    fn generate_line_hover_function(&self) -> String {
        r#"
/**
 * Initialize line hover effects for code blocks
 */
function initializeLineHoverEffects() {
    const codeBlocks = document.querySelectorAll('.code-block');

    codeBlocks.forEach(block => {
        const lines = block.querySelectorAll('.line-number');

        lines.forEach((line, index) => {
            line.addEventListener('mouseenter', function() {
                const lineNumber = parseInt(this.getAttribute('data-line'));
                const codeLines = block.querySelectorAll('code > span');

                // Highlight the current line
                if (codeLines[lineNumber - 1]) {
                    codeLines[lineNumber - 1].style.background = 'rgba(59, 130, 246, 0.1)';
                }
            });

            line.addEventListener('mouseleave', function() {
                const lineNumber = parseInt(this.getAttribute('data-line'));
                const codeLines = block.querySelectorAll('code > span');

                // Remove highlight
                if (codeLines[lineNumber - 1]) {
                    codeLines[lineNumber - 1].style.background = '';
                }
            });
        });
    });
}

"#
        .to_string()
    }

    /// Generate keyboard shortcuts function
    fn generate_keyboard_shortcuts_function(&self) -> String {
        r#"
/**
 * Initialize keyboard shortcuts for code blocks
 */
function initializeKeyboardShortcuts() {
    document.addEventListener('keydown', function(event) {
        // Ctrl/Cmd + K to copy focused code block
        if ((event.ctrlKey || event.metaKey) && event.key === 'k') {
            const focusedElement = document.activeElement;
            const codeBlock = focusedElement.closest('.code-block');

            if (codeBlock) {
                const copyButton = codeBlock.querySelector('.code-copy-button');
                if (copyButton) {
                    event.preventDefault();
                    copyButton.click();
                }
            }
        }
    });
}

"#
        .to_string()
    }

    /// Generate initialization code
    fn generate_initialization(&self) -> String {
        let mut init = String::new();

        init.push_str("/**\n");
        init.push_str(" * Initialize code block enhancements when DOM is ready\n");
        init.push_str(" */\n");
        init.push_str("document.addEventListener('DOMContentLoaded', function() {\n");

        if self.config.enable_line_hover {
            init.push_str("    initializeLineHoverEffects();\n");
        }

        if self.config.enable_keyboard_shortcuts {
            init.push_str("    initializeKeyboardShortcuts();\n");
        }

        init.push_str("});\n\n");

        // Export for external use
        init.push_str("/**\n");
        init.push_str(" * Export functions for external use\n");
        init.push_str(" */\n");
        init.push_str("window.CodeBlockComponent = {\n");

        if self.config.enable_copy {
            init.push_str("    copyCode,\n");
        }

        if self.config.enable_line_hover {
            init.push_str("    initializeLineHoverEffects,\n");
        }

        if self.config.enable_keyboard_shortcuts {
            init.push_str("    initializeKeyboardShortcuts\n");
        }

        init.push_str("};\n");

        init
    }

    /// Set configuration
    pub fn set_config(&mut self, config: JsConfig) {
        self.config = config;
    }

    /// Get configuration
    pub fn config(&self) -> &JsConfig {
        &self.config
    }
}

impl Default for JsGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_js_generation() {
        let generator = JsGenerator::new();
        let js = generator.generate().unwrap();

        assert!(js.contains("function copyCode"));
        assert!(js.contains("function initializeLineHoverEffects"));
        assert!(js.contains("function initializeKeyboardShortcuts"));
        assert!(js.contains("document.addEventListener('DOMContentLoaded'"));
        assert!(js.contains("window.CodeBlockComponent"));
    }

    #[test]
    fn test_js_without_copy() {
        let config = JsConfig {
            enable_copy: false,
            ..Default::default()
        };
        let generator = JsGenerator::with_config(config);
        let js = generator.generate().unwrap();

        assert!(!js.contains("function copyCode"));
    }

    #[test]
    fn test_js_without_keyboard_shortcuts() {
        let config = JsConfig {
            enable_keyboard_shortcuts: false,
            ..Default::default()
        };
        let generator = JsGenerator::with_config(config);
        let js = generator.generate().unwrap();

        assert!(!js.contains("function initializeKeyboardShortcuts"));
    }

    #[test]
    fn test_custom_copy_duration() {
        let config = JsConfig {
            copy_success_duration: 3000,
            ..Default::default()
        };
        let generator = JsGenerator::with_config(config);
        let js = generator.generate().unwrap();

        assert!(js.contains("}, 3000)"));
    }

    #[test]
    fn test_minimal_js() {
        let config = JsConfig {
            enable_copy: false,
            enable_keyboard_shortcuts: false,
            enable_line_hover: false,
            ..Default::default()
        };
        let generator = JsGenerator::with_config(config);
        let js = generator.generate().unwrap();

        assert!(!js.contains("copyCode"));
        assert!(!js.contains("initializeLineHoverEffects"));
        assert!(!js.contains("initializeKeyboardShortcuts"));
    }
}