// Book Content Component JavaScript
document.addEventListener('DOMContentLoaded', function() {
  const bookContentComponents = document.querySelectorAll('[data-component="book_content"]');
  
  bookContentComponents.forEach(function(component) {
    const toggleBtn = component.querySelector('#book-toc-toggle');
    const tocSidebar = component.querySelector('#book-toc-sidebar');
    const tocContent = component.querySelector('.book-toc-content');
    const bookContentWrapper = component.querySelector('.book-content-wrapper');
    
    // Toggle TOC sidebar
    if (toggleBtn && tocSidebar) {
      toggleBtn.addEventListener('click', function() {
        tocSidebar.classList.toggle('active');
        this.classList.toggle('active');
      });
      
      // Close sidebar when clicking outside
      document.addEventListener('click', function(e) {
        if (!tocSidebar.contains(e.target) && !toggleBtn.contains(e.target)) {
          tocSidebar.classList.remove('active');
          toggleBtn.classList.remove('active');
        }
      });
    }
    
    // Extract and populate TOC from toctree HTML (generated by RST parser)
    if (tocContent && bookContentWrapper) {
      // Find toctree elements in the content
      const tocTrees = bookContentWrapper.querySelectorAll('.toc-tree, .toc-caption');
      
      if (tocTrees.length > 0) {
        const tocList = document.createElement('ul');
        
        tocTrees.forEach(function(tocElement) {
          // Handle caption
          if (tocElement.classList.contains('toc-caption')) {
            const captionItem = document.createElement('li');
            captionItem.className = 'toc-caption-item';
            captionItem.textContent = tocElement.textContent.trim();
            tocList.appendChild(captionItem);
          }
          // Handle toc items
          else if (tocElement.classList.contains('toc-tree')) {
            const tocItems = tocElement.querySelectorAll('.toc-item');
            tocItems.forEach(function(tocItem) {
              const link = tocItem.querySelector('a');
              if (link) {
                // Clone the link and keep its href for navigation
                const newLink = link.cloneNode(true);
                const href = newLink.getAttribute('href');
                
                // Check if it's an external link or chapter link
                if (href && !href.startsWith('#') && !href.startsWith('http')) {
                  // It's a chapter link - make it work as normal navigation
                  newLink.addEventListener('click', function(e) {
                    // Let the browser handle the navigation normally
                    // Just close sidebar on mobile
                    if (window.innerWidth <= 768) {
                      tocSidebar.classList.remove('active');
                      toggleBtn.classList.remove('active');
                    }
                  });
                } else if (href && href.startsWith('#')) {
                  // It's an anchor link for scrolling
                  newLink.addEventListener('click', function(e) {
                    e.preventDefault();
                    const targetId = href.substring(1);
                    const targetElement = component.querySelector(`[id="${targetId}"]`);
                    
                    if (targetElement) {
                      targetElement.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                      });
                      history.pushState(null, null, href);
                    }
                    
                    // Close sidebar on mobile
                    if (window.innerWidth <= 768) {
                      tocSidebar.classList.remove('active');
                      toggleBtn.classList.remove('active');
                    }
                  });
                }
                
                const listItem = document.createElement('li');
                listItem.appendChild(newLink);
                tocList.appendChild(listItem);
              }
            });
          }
        });
        
        tocContent.appendChild(tocList);
      } else {
        // Fallback: extract headings if no toctree found (for individual chapter pages)
        const headings = bookContentWrapper.querySelectorAll('h2, h3, h4, h5, h6');
        if (headings.length > 0) {
          const tocList = document.createElement('ul');
          
          headings.forEach(function(heading) {
            const id = heading.getAttribute('id');
            if (!id) return;
            
            const link = document.createElement('a');
            link.href = `#${id}`;
            link.textContent = heading.textContent;
            link.addEventListener('click', function(e) {
              e.preventDefault();
              const targetElement = document.getElementById(id);
              if (targetElement) {
                targetElement.scrollIntoView({
                  behavior: 'smooth',
                  block: 'start'
                });
                history.pushState(null, null, `#${id}`);
              }
              
              // Close sidebar on mobile
              if (window.innerWidth <= 768) {
                tocSidebar.classList.remove('active');
                toggleBtn.classList.remove('active');
              }
            });
            
            const listItem = document.createElement('li');
            listItem.appendChild(link);
            tocList.appendChild(listItem);
          });
          
          tocContent.appendChild(tocList);
        }
      }
    }
    
    // Handle internal links within book content
    const links = component.querySelectorAll('a[href^="#"]');
    links.forEach(function(link) {
      link.addEventListener('click', function(e) {
        e.preventDefault();
        const targetId = this.getAttribute('href').substring(1);
        const targetElement = component.querySelector(`[id="${targetId}"]`);
        
        if (targetElement) {
          targetElement.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
          });
          
          // Update URL hash
          history.pushState(null, null, `#${targetId}`);
        }
      });
    });
    
    // Smooth scroll to hash on page load
    if (window.location.hash) {
      const targetId = window.location.hash.substring(1);
      const targetElement = component.querySelector(`[id="${targetId}"]`);
      if (targetElement) {
        setTimeout(function() {
          targetElement.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
          });
        }, 100);
      }
    }
  });
});