//! JavaScript generator for math formulas

use crate::core::Result;
use serde::{Deserialize, Serialize};

/// JavaScript generator for math formulas
pub struct MathJsGenerator {
    config: MathJsConfig,
}

/// Configuration for math JS generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MathJsConfig {
    /// KaTeX version
    pub katex_version: String,
    /// CDN base URL
    pub cdn_base: String,
    /// Load on demand
    pub load_on_demand: bool,
    /// Auto-render on page load
    pub auto_render: bool,
    /// Debug mode
    pub debug_mode: bool,
    /// Support for modals
    pub modal_support: bool,
}

impl Default for MathJsConfig {
    fn default() -> Self {
        Self {
            katex_version: "0.16.9".to_string(),
            cdn_base: "https://cdn.jsdelivr.net/npm/katex".to_string(),
            load_on_demand: true,
            auto_render: true,
            debug_mode: false,
            modal_support: true,
        }
    }
}

impl MathJsGenerator {
    /// Create a new JS generator with default configuration
    pub fn new() -> Result<Self> {
        Self::with_config(MathJsConfig::default())
    }

    /// Create a JS generator with custom configuration
    pub fn with_config(config: MathJsConfig) -> Result<Self> {
        Ok(Self { config })
    }

    /// Generate complete JavaScript for math formulas
    pub fn generate(&self) -> Result<String> {
        let mut js = String::new();

        // Header
        js.push_str("/**\n");
        js.push_str(" * Math Formula Rendering\n");
        js.push_str(" * Generated by Peta Static Site Generator\n");
        js.push_str(" */\n\n");

        // IIFE to avoid global pollution
        js.push_str("(function() {\n");
        js.push_str("'use strict';\n\n");

        // State management
        js.push_str(&self.generate_state_management());
        js.push('\n');

        // Loader
        js.push_str(&self.generate_loader());
        js.push('\n');

        // Renderer
        js.push_str(&self.generate_renderer());
        js.push('\n');

        // Modal support
        if self.config.modal_support {
            js.push_str(&self.generate_modal_support());
            js.push('\n');
        }

        // Auto-render
        if self.config.auto_render {
            js.push_str(&self.generate_auto_render());
            js.push('\n');
        }

        // Error handler
        js.push_str(&self.generate_error_handler());
        js.push('\n');

        // Close IIFE
        js.push_str("})();\n");

        Ok(js)
    }

    /// Generate state management
    fn generate_state_management(&self) -> String {
        format!(
            r#"// State management
if (typeof window.petaMathLoaded === 'undefined') {{
    window.petaMathLoaded = false;
    window.petaMathPending = false;
}}

{}"#,
            if self.config.debug_mode {
                "console.log('[Peta Math] Initialized');".to_string()
            } else {
                String::new()
            }
        )
    }

    /// Generate loader
    fn generate_loader(&self) -> String {
        let css_url = format!(
            "{}@{}/dist/katex.min.css",
            self.config.cdn_base, self.config.katex_version
        );
        let js_url = format!(
            "{}@{}/dist/katex.min.js",
            self.config.cdn_base, self.config.katex_version
        );
        let auto_render_url = format!(
            "{}@{}/dist/contrib/auto-render.min.js",
            self.config.cdn_base, self.config.katex_version
        );

        format!(
            r#"// Load KaTeX on demand
function loadKaTeX() {{
    if (window.petaMathLoaded) {{
        return Promise.resolve();
    }}

    return new Promise(function(resolve, reject) {{
        // Load CSS
        if (!document.querySelector('link[href*="katex.min.css"]')) {{
            const css = document.createElement('link');
            css.rel = 'stylesheet';
            css.href = '{}';
            document.head.appendChild(css);
        }}

        // Load KaTeX JS
        const katex = document.createElement('script');
        katex.src = '{}';
        katex.async = true;

        katex.onload = function() {{
            // Load auto-render extension
            const autoRender = document.createElement('script');
            autoRender.src = '{}';
            autoRender.async = true;

            autoRender.onload = function() {{
                window.petaMathLoaded = true;
                {}
                resolve();
            }};

            autoRender.onerror = reject;
            document.body.appendChild(autoRender);
        }};

        katex.onerror = reject;
        document.body.appendChild(katex);
    }});
}}
"#,
            css_url,
            js_url,
            auto_render_url,
            if self.config.debug_mode {
                "console.log('[Peta Math] KaTeX loaded');"
            } else {
                ""
            }
        )
    }

    /// Generate renderer
    fn generate_renderer(&self) -> String {
        r#"// Render math elements
function renderMath() {
    if (!window.petaMathLoaded) {
        window.petaMathPending = true;
        loadKaTeX().then(renderMath).catch(handleError);
        return;
    }

    const elements = document.querySelectorAll('[data-latex]');
    elements.forEach(function(el) {
        const latex = el.getAttribute('data-latex');
        if (latex && window.katex) {
            try {
                el.innerHTML = '';
                window.katex.render(latex, el, {
                    displayMode: el.classList.contains('math-display'),
                    throwOnError: false,
                    trust: true
                });
            } catch (e) {
                handleError(e, el);
            }
        }
    });
}
"#.to_string()
    }

    /// Generate modal support
    fn generate_modal_support(&self) -> String {
        r#"// Modal support - render math when modal opens
function setupModalSupport() {
    // Observer for DOM changes (for dynamic content)
    const observer = new MutationObserver(function(mutations) {
        mutations.forEach(function(mutation) {
            mutation.addedNodes.forEach(function(node) {
                if (node.nodeType === 1) { // Element node
                    const mathElements = node.querySelectorAll ? 
                        node.querySelectorAll('[data-latex]') : [];
                    if (mathElements.length > 0) {
                        renderMath();
                    }
                }
            });
        });
    });

    observer.observe(document.body, {
        childList: true,
        subtree: true
    });

    return observer;
}

setupModalSupport();
"#.to_string()
    }

    /// Generate auto-render
    fn generate_auto_render(&self) -> String {
        r#"// Auto-render on page load
function autoRender() {
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', renderMath);
    } else {
        renderMath();
    }
}

autoRender();
"#.to_string()
    }

    /// Generate error handler
    fn generate_error_handler(&self) -> String {
        format!(
            r#"// Error handling
function handleError(error, element) {{
    if (element) {{
        element.innerHTML = element.getAttribute('data-latex');
        element.classList.add('math-error');
    }}
    {}
}}

// Global error handler for unhandled promise rejections
window.addEventListener('unhandledrejection', function(event) {{
    if (event.reason) {{
        handleError(event.reason);
    }}
}});
"#,
            if self.config.debug_mode {
                "console.error('[Peta Math] Error:', error);"
            } else {
                ""
            }
        )
    }

    /// Set debug mode
    pub fn set_debug_mode(&mut self, debug: bool) {
        self.config.debug_mode = debug;
    }

    /// Get configuration
    pub fn config(&self) -> &MathJsConfig {
        &self.config
    }
}

impl Default for MathJsGenerator {
    fn default() -> Self {
        Self::new().expect("Failed to create MathJsGenerator")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_js_generator() {
        let generator = MathJsGenerator::new().unwrap();
        let js = generator.generate().unwrap();

        assert!(js.contains("function loadKaTeX()"));
        assert!(js.contains("function renderMath()"));
        assert!(js.contains("window.petaMathLoaded"));
        assert!(js.contains("MutationObserver"));
    }

    #[test]
    fn test_debug_mode() {
        let mut config = MathJsConfig::default();
        config.debug_mode = true;
        let generator = MathJsGenerator::with_config(config).unwrap();
        let js = generator.generate().unwrap();

        assert!(js.contains("console.log('[Peta Math] Initialized')"));
        assert!(js.contains("console.log('[Peta Math] KaTeX loaded')"));
        assert!(js.contains("console.error('[Peta Math] Error:'"));
    }

    #[test]
    fn test_no_modal_support() {
        let mut config = MathJsConfig::default();
        config.modal_support = false;
        let generator = MathJsGenerator::with_config(config).unwrap();
        let js = generator.generate().unwrap();

        assert!(!js.contains("setupModalSupport"));
        assert!(!js.contains("MutationObserver"));
    }
}
